[build]
publish = "dist"
command = "npm run build"

[[headers]]
for = "/*"
[headers.values]
  Strict-Transport-Security = "max-age=63072000"
  Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
